io/writer.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat: add ioz package

errors/fmt.go, errors/fmt_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix: fix errors suffix detection

.github/workflows/go-lint.yml, .github/workflows/go-mod-tidy.yml, .github/workflows/go-test.yml, .github/workflows/go-vuln.yml
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> chore: fix misc

exp/diff/simplediff/diff.go, exp/diff/simplediff/diff_test.go, testing/assert/assert.go, testing/internal/common.go, testing/require/require.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat: add simplediff package

strings/prefix.go, strings/prefix_test.go, testing/assert/assert.go, testing/internal/common.go, testing/require/require.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat: add assert, require packages

generics/pointer.go, generics/pointer_test.go, generics/zero.go, generics/zero_test.go, testing/internal/common.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix: fix testingz/internal.Error func

testing/assert/assert.go, testing/internal/common.go, testing/require/require.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> chore: fix misc in testingz package

exp/cli/cli.go, exp/cli/cli_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat: add (*cliz.Command).Next()

exp/cli/command_test.go, exp/cli/context.go, exp/cli/context_test.go, exp/cli/errors.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix: fix cli context misc

exp/cli/command.go, exp/cli/command_test.go, exp/cli/help.go, exp/cli/option.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix: fix cli misc

testing/assert/assert.go, testing/assert/doc.go, testing/internal/common.go, testing/require/doc.go, testing/require/require.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix: fix testing/* packages

.github/workflows/label-checker.yml
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> chore: add comment

generics/zero.go, generics/zero_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat: add genericz.SliceContentZero() func

version/version.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat: Add version package

os/os.go, os/os_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat(os): implement osz.IsFile() func

.bin/git-tag-go-mod.sh
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> chore: fix git-tag-go-mod.sh

testing/os.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat(testing): add NewFileWriter() func

exp/database/sql/util/mysql/show_create_all_tables.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix(exp/database/sql/util/mysql): fix MySQL SHOW CREATE TABLE schema def

exp/database/sql/ddl/cockroachdb/parser.go, exp/database/sql/ddl/postgres/parser.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> refactor(exp/database/sql/ddl/postgres): fix checkCurrentToken() and checkPeekToken()

database/sql/queryer.go, database/sql/queryer_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix: return rows.Close() err

database/sql/mock_test.go, database/sql/queryer_test.go, database/sql/rows.go, database/sql/rows_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix: return rows.Err() err

exp/cli/command.go, exp/cli/command_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix(exp/cli): fix WithContext args for subcommand

strings/read_line.go, strings/read_line_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat: add ReadLine() func

.github/workflows/go-lint.yml, integrationtest/internal/database/sql/spanner/spanner_test.go, net/net.go, openid/openidtest/openidtest.go, retry/retry.go, retry/retry_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix: fix lint

jose/jwa/jws.go, jose/jwa/jws_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> BREAKING CHANGE: fix jose/jwa

errors/errors.go, errors/errors_test.go, errors/retryable.go, errors/retryable_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat: add func IsNetTimeout

.github/workflows/go-mod-tidy.yml
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> ci: fix .github/workflows/go-mod-tidy.yml for dependabot

.github/workflows/go-mod-tidy.yml
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> ci: fix misc

.github/dependabot.yml
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> ci: Modify Dependabot's update interval from daily to weekly

retry/retry.go, retry/retry_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> BREAKING CHANGE(retry): Modify DefaultJitter func

grpc/go.mod, grpc/go.sum, grpc/grpc-gateway/register.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> feat(grpc/grpc-gateway): Add grpcgateway package

testing/internal/common.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> fix: Fix testing/internal.NotNil for log

retry/retry.go, retry/retry_test.go
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> BREAKING CHANGE: Fix retry.Retryer for ctx handling

.gitattributes
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> chore: Create .gitattributes

.github/workflows/go-lint-skip.yml, .github/workflows/go-test-skip.yml
> **Note**
> > Example:
> >
> > #3
> **Note**
> > Example:
> >
> **Note**
=> ci: Fix paths-ignore conditions for lint and test
